/**
 * Printers for the three outputs. Pure functions of the validated model, so
 * they are deterministic (byte-identical across runs and machines), which CI
 * relies on to detect stale generated files.
 */
import type { Rgb } from "./color.ts";
import { COLOR_NAMES, THEME_IDS, type ColorName, type ResolvedColor, type ThemeModel, type TokenMeta } from "./model.ts";

const SOURCE = "packages/tokens/tokens.json";
const REGEN = "pnpm --filter @sanad/tokens build";

/** Fixed 6-decimal rendering shared by TS and Rust, so both carry identical values. */
function fixed6(x: number): string {
  const s = String(Number(x.toFixed(6)));
  return s === "-0" ? "0" : s;
}

// ---------------------------------------------------------------- CSS ------

export const CSS_VARS = [...COLOR_NAMES.map((n) => `--${n}` as const), "--focus-ring"] as const;
export type CssVar = (typeof CSS_VARS)[number];

function cssColor(c: ResolvedColor): string {
  if (c.alpha === 1) return c.hex;
  const [r, g, b] = [1, 3, 5].map((i) => Number.parseInt(c.hex.slice(i, i + 2), 16));
  return `rgb(${r} ${g} ${b} / ${c.alpha})`;
}

function oklchComment(c: ResolvedColor): string {
  const [l, ch, h] = c.oklch;
  const alpha = c.alpha === 1 ? "" : ` / ${c.alpha}`;
  return `oklch(${Number((l * 100).toFixed(2))}% ${ch} ${h}${alpha})`;
}

/** CSS custom property values of one theme, keyed by property name. */
export function cssValues(m: ThemeModel): Readonly<Record<CssVar, string>> {
  const out = Object.fromEntries(COLOR_NAMES.map((n) => [`--${n}`, cssColor(m.colors[n])])) as Record<CssVar, string>;
  const r = m.focusRing;
  const px = (n: number): string => (n === 0 ? "0" : `${n}px`);
  out["--focus-ring"] = `${px(r.offsetX)} ${px(r.offsetY)} ${px(r.blur)} ${px(r.spread)} ${cssColor(r.color)}`;
  return out;
}

function cssBlock(selector: string, m: ThemeModel, indent = ""): string {
  const values = cssValues(m);
  const lines = [`${indent}${selector} {`, `${indent}  color-scheme: ${m.mode};`];
  for (const v of CSS_VARS) {
    const name = v.slice(2) as ColorName | "focus-ring";
    const comment = name === "focus-ring" ? "" : ` /* ${oklchComment(m.colors[name])} */`;
    lines.push(`${indent}  ${v}: ${values[v]};${comment}`);
  }
  lines.push(`${indent}}`);
  return lines.join("\n");
}

export function formatCss(models: readonly ThemeModel[], meta: TokenMeta): string {
  const byId = new Map(models.map((m) => [m.id, m]));
  const theme = (id: (typeof THEME_IDS)[number]): ThemeModel => {
    const m = byId.get(id);
    if (m === undefined) throw new Error(`missing theme ${id}`);
    return m;
  };
  const blocks = THEME_IDS.map((id) => {
    const selector = id === meta.defaults.light ? `:root,\n[data-theme="${id}"]` : `[data-theme="${id}"]`;
    return cssBlock(selector, theme(id));
  });
  return [
    `/* @generated by @sanad/tokens from ${SOURCE} (format sanad/css-themes). Do not edit: ${REGEN}. */`,
    `/* Values are the shipped hex; the comment is the authoritative OKLCH. Lumen's Pass 3 receives the same hex, linearized. */`,
    "",
    blocks.join("\n\n"),
    "",
    `/* No explicit theme: follow the OS color scheme. */`,
    `@media (prefers-color-scheme: dark) {`,
    cssBlock(":root:not([data-theme])", theme(meta.defaults.dark), "  "),
    `}`,
    "",
  ].join("\n");
}

// ------------------------------------------------------------- shared ------

interface Uniforms {
  readonly paper: Rgb;
  readonly ink: Rgb;
  readonly ink2: Rgb;
  readonly accent: Rgb;
  readonly highlights: readonly [Rgb, Rgb, Rgb, Rgb];
  readonly covGamma: number;
  readonly weightPx: number;
  readonly lumaCeil: number;
}

export function uniformsOf(m: ThemeModel): Uniforms {
  const c = m.colors;
  return {
    paper: c.paper.linear,
    ink: c.ink.linear,
    ink2: c["ink-2"].linear,
    accent: c.accent.linear,
    highlights: [c["highlight-1"].linear, c["highlight-2"].linear, c["highlight-3"].linear, c["highlight-4"].linear],
    covGamma: m.shader.covGamma,
    weightPx: m.shader.weightPx,
    lumaCeil: m.shader.lumaCeil,
  };
}

// ----------------------------------------------------------------- TS ------

const tsRgb = (v: Rgb): string => `[${v.map(fixed6).join(", ")}]`;

function tsTheme(m: ThemeModel): string {
  const u = uniformsOf(m);
  const css = cssValues(m);
  return [
    `  ${m.id}: {`,
    `    id: "${m.id}",`,
    `    label: ${JSON.stringify(m.label)},`,
    `    mode: "${m.mode}",`,
    `    imagePolicy: "${m.imagePolicy}",`,
    `    css: {`,
    ...CSS_VARS.map((v) => `      "${v}": ${JSON.stringify(css[v])},`),
    `    },`,
    `    uniforms: {`,
    `      paper: ${tsRgb(u.paper)},`,
    `      ink: ${tsRgb(u.ink)},`,
    `      ink2: ${tsRgb(u.ink2)},`,
    `      accent: ${tsRgb(u.accent)},`,
    `      highlights: [${u.highlights.map(tsRgb).join(", ")}],`,
    `      covGamma: ${fixed6(u.covGamma)},`,
    `      weightPx: ${fixed6(u.weightPx)},`,
    `      lumaCeil: ${fixed6(u.lumaCeil)},`,
    `    },`,
    `  },`,
  ].join("\n");
}

export function formatTs(models: readonly ThemeModel[], meta: TokenMeta): string {
  const q = (s: string): string => JSON.stringify(s);
  return `// @generated by @sanad/tokens from ${SOURCE} (format sanad/ts-themes). Do not edit: ${REGEN}.

export type Rgb = readonly [number, number, number];
export type ThemeId = ${THEME_IDS.map(q).join(" | ")};
export type ThemeMode = "light" | "dark";
export type ImagePolicy = "natural" | "dimmed" | "smart-invert";
export type CssVar =
${CSS_VARS.map((v) => `  | ${q(v)}`).join("\n")};

/**
 * Theme-owned uniforms of Lumen's Pass 3 composite. Colors are LINEAR sRGB of
 * the shipped hex, so the page renders exactly the CSS chrome colors. Warmth
 * and extra-dim are reader settings and are supplied by Lumen.
 */
export interface ThemeShaderUniforms {
  readonly paper: Rgb;
  readonly ink: Rgb;
  readonly ink2: Rgb;
  readonly accent: Rgb;
  readonly highlights: readonly [Rgb, Rgb, Rgb, Rgb];
  /** Coverage curve exponent. */
  readonly covGamma: number;
  /** Optical weight compensation: edge offset in screen px (+ bolder, − thinner). */
  readonly weightPx: number;
  /** Anti-glare luminance ceiling (linear Y); never below any palette color. */
  readonly lumaCeil: number;
}

export interface ThemeTokens {
  readonly id: ThemeId;
  readonly label: string;
  readonly mode: ThemeMode;
  /** Default dark-mode image treatment (the reader may override it). */
  readonly imagePolicy: ImagePolicy;
  /** Custom property values, identical to themes.css. */
  readonly css: Readonly<Record<CssVar, string>>;
  readonly uniforms: ThemeShaderUniforms;
}

export const THEME_IDS: readonly ThemeId[] = [${THEME_IDS.map(q).join(", ")}];

/** Theme used when none is chosen, per \`prefers-color-scheme\`. */
export const DEFAULT_THEME: { readonly light: ThemeId; readonly dark: ThemeId } = { light: ${q(meta.defaults.light)}, dark: ${q(meta.defaults.dark)} };

export const THEMES: Readonly<Record<ThemeId, ThemeTokens>> = {
${models.map(tsTheme).join("\n")}
};
`;
}

// --------------------------------------------------------------- Rust ------

function rustF32(x: number): string {
  const s = fixed6(x);
  return s.includes(".") ? s : `${s}.0`;
}

const rustRgb = (v: Rgb): string => `[${v.map(rustF32).join(", ")}]`;
const rustConst = (id: string): string => id.toUpperCase();
const rustVariant = (id: string): string => id.charAt(0).toUpperCase() + id.slice(1);

function rustTheme(m: ThemeModel): string {
  const u = uniformsOf(m);
  return `/// ${m.label} (${m.mode}).
pub const ${rustConst(m.id)}: ThemeUniforms = ThemeUniforms {
    paper: ${rustRgb(u.paper)},
    ink: ${rustRgb(u.ink)},
    ink2: ${rustRgb(u.ink2)},
    accent: ${rustRgb(u.accent)},
    highlights: [
${u.highlights.map((h) => `        ${rustRgb(h)},`).join("\n")}
    ],
    cov_gamma: ${rustF32(u.covGamma)},
    weight_px: ${rustF32(u.weightPx)},
    luma_ceil: ${rustF32(u.lumaCeil)},
};`;
}

export function formatRust(models: readonly ThemeModel[]): string {
  const ids = models.map((m) => m.id);
  return `// @generated by @sanad/tokens from ${SOURCE} (format sanad/rust-uniforms).
// Do not edit: ${REGEN}. CI fails if this file is stale.
#![allow(clippy::unreadable_literal)]

/// Theme-owned uniforms of Lumen's Pass 3 composite.
///
/// Colors are LINEAR sRGB of the shipped hex, so a renderer fed these values
/// produces exactly the CSS chrome colors. Warmth and extra-dim are reader
/// settings, not theme tokens.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ThemeUniforms {
    pub paper: [f32; 3],
    pub ink: [f32; 3],
    pub ink2: [f32; 3],
    pub accent: [f32; 3],
    pub highlights: [[f32; 3]; 4],
    /// Coverage curve exponent.
    pub cov_gamma: f32,
    /// Optical weight compensation: edge offset in screen px (+ bolder, − thinner).
    pub weight_px: f32,
    /// Anti-glare luminance ceiling (linear Y); never below any palette color.
    pub luma_ceil: f32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThemeId {
${ids.map((id) => `    ${rustVariant(id)},`).join("\n")}
}

impl ThemeId {
    pub const ALL: [Self; ${ids.length}] = [
${ids.map((id) => `        Self::${rustVariant(id)},`).join("\n")}
    ];

    /// The id used by \`data-theme\` and the token tree.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
${ids.map((id) => `            Self::${rustVariant(id)} => "${id}",`).join("\n")}
        }
    }

    #[must_use]
    pub fn parse(id: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|t| t.as_str() == id)
    }

    #[must_use]
    pub const fn is_dark(self) -> bool {
        matches!(self, ${models.filter((m) => m.mode === "dark").map((m) => `Self::${rustVariant(m.id)}`).join(" | ")})
    }

    #[must_use]
    pub const fn uniforms(self) -> &'static ThemeUniforms {
        match self {
${ids.map((id) => `            Self::${rustVariant(id)} => &${rustConst(id)},`).join("\n")}
        }
    }
}

${models.map(rustTheme).join("\n\n")}
`;
}
