/**
 * The reader's decode path on a chunk sealed by Atelier: AES-GCM open, zstd
 * inflate, FlatBuffer parse. Proves the client recovers exactly the permuted
 * runs Atelier sealed, across the P1 boundary and across languages (Rust →
 * TypeScript). The fixture is regenerated by
 * `cargo run -p sanad-atelier --example seal_reader_fixture`.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { parseChunk } from "../src/vault/folio.ts";
import { BLOCK_KINDS, openFlowChunk, parseFlowChunk } from "../src/vault/flow.ts";

const dir = fileURLToPath(new URL("../../../fixtures/folio/", import.meta.url));
const sealed = new Uint8Array(readFileSync(`${dir}canary-chunk0-v0.folio`));
const expected = JSON.parse(readFileSync(`${dir}canary-chunk0-v0.expected.json`, "utf8")) as {
  editionId: string;
  chunkIndex: number;
  variant: number;
  chunkKeyHex: string;
  payload: {
    blocks: {
      kind: number;
      dir: number;
      runs: { font: number; gids: number[]; advances: number[]; flags: number[]; bidiLevels: number[] }[];
    }[];
  };
};

function keyBytes(hex: string): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(hex.slice(2 * i, 2 * i + 2), 16);
  return out;
}

async function chunkKey(): Promise<CryptoKey> {
  // The lease delivers a non-extractable, decrypt-only AES-GCM key. The dev
  // fixture ships the raw bytes so the test can import the same key.
  return crypto.subtle.importKey("raw", keyBytes(expected.chunkKeyHex), "AES-GCM", false, ["decrypt"]);
}

test("the chunk key opens the sealed chunk and recovers every run", async () => {
  const header = parseChunk(sealed);
  assert.equal(header.editionId, expected.editionId);
  assert.equal(header.chunkIndex, expected.chunkIndex);
  assert.equal(header.kind, "flow");

  const want = { kind: "flow", editionId: expected.editionId, chunkIndex: 0, variant: 0 } as const;
  const flow = await openFlowChunk(await chunkKey(), sealed, want, header.flags);

  assert.equal(flow.blocks.length, expected.payload.blocks.length, "block count");
  flow.blocks.forEach((block, b) => {
    const want = expected.payload.blocks[b]!;
    assert.equal(block.kind, BLOCK_KINDS[want.kind], `block ${b} kind`);
    assert.equal(block.dir, want.dir === 1 ? "rtl" : "ltr", `block ${b} dir`);
    assert.equal(block.runs.length, want.runs.length, `block ${b} run count`);
    block.runs.forEach((run, r) => {
      const wr = want.runs[r]!;
      assert.equal(run.font, wr.font, `block ${b} run ${r} font`);
      assert.deepEqual([...run.gids], wr.gids, `block ${b} run ${r} gids`);
      assert.deepEqual([...run.advances], wr.advances, `block ${b} run ${r} advances`);
      assert.deepEqual([...run.flags], wr.flags, `block ${b} run ${r} flags`);
      assert.deepEqual([...run.bidiLevels], wr.bidiLevels, `block ${b} run ${r} bidi`);
    });
  });
});

test("the gids are permuted ids, never Unicode or sequential glyph ids", () => {
  // A sanity check on the fixture itself: ids are spread across the 16-bit
  // space, not small or contiguous (which permutation guarantees).
  const gids = expected.payload.blocks.flatMap((b) => b.runs.flatMap((r) => r.gids));
  assert.ok(gids.length > 50);
  assert.ok(Math.max(...gids) > 20000, "permuted ids reach high into the id space");
  const distinct = new Set(gids);
  assert.ok(distinct.size > 20, "many distinct glyphs");
});

test("the wrong key fails authentication (AEAD)", async () => {
  const bad = await crypto.subtle.importKey("raw", new Uint8Array(32), "AES-GCM", false, ["decrypt"]);
  const want = { kind: "flow", editionId: expected.editionId, chunkIndex: 0, variant: 0 } as const;
  await assert.rejects(openFlowChunk(bad, sealed, want, parseChunk(sealed).flags));
});

test("parseFlowChunk rejects non-FlowChunk input", () => {
  assert.throws(() => parseFlowChunk(new Uint8Array(8)));
});
