/**
 * The manifest reader on a manifest signed by Atelier (crates/atelier
 * seal_edition): the client verifies the Ed25519 signature (WebCrypto) against
 * the pinned publisher key and only then trusts the structure and atlas
 * geometry. Proves cross-language signing (Rust aws-lc-rs → TS WebCrypto),
 * that a tampered byte or a wrong key is rejected, and that the manifest's
 * atlas page lays out through the same GlyphTable the renderer uses. The
 * fixture is regenerated by
 * `cargo run -p sanad-atelier --example seal_reader_fixture`.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { glyphTableFromManifest } from "../src/reader/layout.ts";
import {
  MANIFEST_SCHEMA,
  ManifestError,
  chunk,
  openManifest,
  page,
  parseManifest,
  verifyManifestSignature,
} from "../src/vault/manifest.ts";

const dir = fileURLToPath(new URL("../../../fixtures/folio/", import.meta.url));
const bytes = new Uint8Array(readFileSync(`${dir}canary-manifest.json`));
const sig = new Uint8Array(readFileSync(`${dir}canary-manifest.sig`));
const pub = new Uint8Array(readFileSync(`${dir}canary-manifest.pub`));

const EDITION = "00000000-0000-7000-8000-00000000ca7a";

test("a manifest signed by Atelier verifies against the pinned key", async () => {
  assert.equal(pub.length, 32, "raw Ed25519 public key");
  assert.equal(sig.length, 64, "Ed25519 signature");
  assert.equal(await verifyManifestSignature(bytes, sig, pub), true);
});

test("openManifest verifies then parses into the typed structure", async () => {
  const m = await openManifest(bytes, sig, pub);
  assert.equal(m.schema, MANIFEST_SCHEMA);
  assert.equal(m.editionId, EDITION);
  assert.equal(m.kind, "flow");
  assert.equal(m.variants, 2);
  assert.deepEqual([...m.fonts], ["latin", "arabic"]);
  assert.ok(m.chunks.length > 0 && m.atlas.length > 0);

  // Chunk lookup by (index, variant); both variants of chapter 0 are present.
  const a = chunk(m, 0, 0);
  const b = chunk(m, 0, 1);
  if (a === undefined || b === undefined) throw new Error("both variants of chunk 0 must exist");
  assert.equal(a.chapter, 0);
  assert.notEqual(a.path, b.path, "A/B variants have distinct opaque paths");
  assert.match(a.path, /\.folio$/u);
  assert.equal(chunk(m, 9999, 0), undefined);
});

test("a tampered manifest body is rejected", async () => {
  const flipped = bytes.slice();
  const i = flipped.length - 20; // a byte well inside the JSON
  flipped[i] = (flipped[i] ?? 0) ^ 0x01;
  assert.equal(await verifyManifestSignature(flipped, sig, pub), false);
  await assert.rejects(() => openManifest(flipped, sig, pub), ManifestError);
});

test("a wrong public key does not verify", async () => {
  const wrong = pub.slice();
  wrong[0] = (wrong[0] ?? 0) ^ 0xff;
  // A flipped key may be a valid point (verify → false) or invalid (throws);
  // either way it never authenticates the manifest.
  let authenticated = false;
  try {
    authenticated = await verifyManifestSignature(bytes, sig, wrong);
  } catch (e) {
    assert.ok(e instanceof ManifestError);
  }
  assert.equal(authenticated, false);
});

test("the manifest's atlas page lays out through the renderer's GlyphTable", async () => {
  const m = await openManifest(bytes, sig, pub);
  const p0 = page(m, 0);
  if (p0 === undefined) throw new Error("atlas page 0 must be present");
  const table = glyphTableFromManifest(p0, m.pxRange);
  assert.equal(table.width, p0.width);
  assert.equal(table.height, p0.height);
  assert.equal(table.pxRange, m.pxRange);
  assert.equal(table.glyphs.size, p0.glyphs.length);

  // Every glyph's fragment slots lie on the atlas page (the signed geometry).
  for (const g of table.glyphs.values()) {
    for (const [x, y, w, h] of g.slots) {
      assert.ok(x >= 0 && y >= 0 && x + w <= table.width && y + h <= table.height, "slot on atlas");
    }
  }
});

test("parseManifest rejects an unsupported schema", () => {
  const tweaked = JSON.stringify({ ...JSON.parse(Buffer.from(bytes).toString("utf8")), schema: 999 });
  assert.throws(() => parseManifest(tweaked), ManifestError);
});
