//! # Marginalia theme tokens
//!
//! The Rust view of `packages/tokens/tokens.json`: the theme-owned uniforms of
//! Lumen's Pass 3 composite, for native renderers and offline tools (golden
//! pages, publisher proofs). `theme_uniforms.rs` is generated by Style
//! Dictionary (`packages/tokens/sd-config.js`, format `sanad/rust-uniforms`)
//! and committed so Cargo builds never depend on Node; CI rebuilds it and fails
//! on any difference.
//!
//! Spec: `docs/blueprint/04-design-system.md` §4.

#![no_std]

mod theme_uniforms;

pub use theme_uniforms::{DUSK, LINEN, NIGHT, OLED, PAPER, ThemeId, ThemeUniforms};

/// WCAG 2.x relative luminance (linear Y) of a linear sRGB color; the same
/// weights the composite uses for its anti-glare ceiling.
#[must_use]
pub fn luminance([r, g, b]: [f32; 3]) -> f32 {
    0.2126 * r + 0.7152 * g + 0.0722 * b
}

impl ThemeUniforms {
    /// Every color the composite can draw without images: paper, the three
    /// ink roles and the four highlight underlays.
    #[must_use]
    pub fn palette(&self) -> [[f32; 3]; 8] {
        let [h1, h2, h3, h4] = self.highlights;
        [self.paper, self.ink, self.ink2, self.accent, h1, h2, h3, h4]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ceiling_never_dims_the_palette() {
        // The ceiling scales whole pixels; if it touched a palette color the
        // page would stop matching the CSS chrome.
        for id in ThemeId::ALL {
            let u = id.uniforms();
            for c in u.palette() {
                assert!(
                    luminance(c) <= u.luma_ceil,
                    "{}: Y {} > ceiling {}",
                    id.as_str(),
                    luminance(c),
                    u.luma_ceil
                );
            }
        }
    }

    #[test]
    fn dark_ceiling_is_the_ink_luminance() {
        // No image pixel may outshine the text in a dark theme.
        for id in ThemeId::ALL.into_iter().filter(|t| t.is_dark()) {
            let u = id.uniforms();
            let slack = u.luma_ceil - luminance(u.ink);
            assert!(
                (0.0..=0.01).contains(&slack),
                "{}: slack {slack}",
                id.as_str()
            );
        }
    }

    #[test]
    fn weight_thins_light_on_dark_only() {
        for id in ThemeId::ALL {
            let w = id.uniforms().weight_px;
            assert_eq!(id.is_dark(), w < 0.0, "{}: weight {w}", id.as_str());
            assert!(w.abs() <= 0.5);
        }
    }

    #[test]
    fn ids_round_trip() {
        for id in ThemeId::ALL {
            assert_eq!(ThemeId::parse(id.as_str()), Some(id));
        }
        assert_eq!(ThemeId::parse("sepia"), None);
        assert_eq!(*ThemeId::Night.uniforms(), NIGHT);
    }
}
