// @generated by @sanad/tokens from packages/tokens/tokens.json (format sanad/rust-uniforms).
// Do not edit: pnpm --filter @sanad/tokens build. CI fails if this file is stale.
#![allow(clippy::unreadable_literal)]

/// Theme-owned uniforms of Lumen's Pass 3 composite.
///
/// Colors are LINEAR sRGB of the shipped hex, so a renderer fed these values
/// produces exactly the CSS chrome colors. Warmth and extra-dim are reader
/// settings, not theme tokens.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ThemeUniforms {
    pub paper: [f32; 3],
    pub ink: [f32; 3],
    pub ink2: [f32; 3],
    pub accent: [f32; 3],
    pub highlights: [[f32; 3]; 4],
    /// Coverage curve exponent.
    pub cov_gamma: f32,
    /// Optical weight compensation: edge offset in screen px (+ bolder, − thinner).
    pub weight_px: f32,
    /// Anti-glare luminance ceiling (linear Y); never below any palette color.
    pub luma_ceil: f32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThemeId {
    Paper,
    Linen,
    Dusk,
    Night,
    Oled,
}

impl ThemeId {
    pub const ALL: [Self; 5] = [
        Self::Paper,
        Self::Linen,
        Self::Dusk,
        Self::Night,
        Self::Oled,
    ];

    /// The id used by `data-theme` and the token tree.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Paper => "paper",
            Self::Linen => "linen",
            Self::Dusk => "dusk",
            Self::Night => "night",
            Self::Oled => "oled",
        }
    }

    #[must_use]
    pub fn parse(id: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|t| t.as_str() == id)
    }

    #[must_use]
    pub const fn is_dark(self) -> bool {
        matches!(self, Self::Dusk | Self::Night | Self::Oled)
    }

    #[must_use]
    pub const fn uniforms(self) -> &'static ThemeUniforms {
        match self {
            Self::Paper => &PAPER,
            Self::Linen => &LINEN,
            Self::Dusk => &DUSK,
            Self::Night => &NIGHT,
            Self::Oled => &OLED,
        }
    }
}

/// Paper (light).
pub const PAPER: ThemeUniforms = ThemeUniforms {
    paper: [0.964686, 0.955973, 0.930111],
    ink: [0.012286, 0.011612, 0.01033],
    ink2: [0.111932, 0.102242, 0.0865],
    accent: [0.028426, 0.109462, 0.254152],
    highlights: [
        [0.930111, 0.806952, 0.371238],
        [0.62396, 0.83077, 0.584078],
        [0.62396, 0.745404, 0.913099],
        [0.913099, 0.651406, 0.715694],
    ],
    cov_gamma: 0.9,
    weight_px: 0.05,
    luma_ceil: 1.0,
};

/// Linen (light).
pub const LINEN: ThemeUniforms = ThemeUniforms {
    paper: [0.896269, 0.83077, 0.723055],
    ink: [0.027321, 0.019382, 0.012286],
    ink2: [0.144128, 0.109462, 0.072272],
    accent: [0.254152, 0.07036, 0.023153],
    highlights: [
        [0.854993, 0.686685, 0.323143],
        [0.62396, 0.745404, 0.47932],
        [0.584078, 0.686685, 0.791298],
        [0.838799, 0.597202, 0.552011],
    ],
    cov_gamma: 0.9,
    weight_px: 0.05,
    luma_ceil: 0.92,
};

/// Dusk (dark).
pub const DUSK: ThemeUniforms = ThemeUniforms {
    paper: [0.023153, 0.023153, 0.026241],
    ink: [0.701102, 0.672443, 0.617207],
    ink2: [0.361307, 0.341914, 0.304987],
    accent: [0.337164, 0.47932, 0.693872],
    highlights: [
        [0.064803, 0.057805, 0.023153],
        [0.027321, 0.061246, 0.03434],
        [0.027321, 0.048172, 0.084376],
        [0.072272, 0.033105, 0.045186],
    ],
    cov_gamma: 1.1,
    weight_px: -0.12,
    luma_ceil: 0.68,
};

/// Night (dark).
pub const NIGHT: ThemeUniforms = ThemeUniforms {
    paper: [0.006995, 0.006995, 0.006995],
    ink: [0.62396, 0.590619, 0.533276],
    ink2: [0.274677, 0.254152, 0.223228],
    accent: [0.274677, 0.396755, 0.584078],
    highlights: [
        [0.046665, 0.040915, 0.011612],
        [0.016807, 0.042311, 0.021219],
        [0.015996, 0.030713, 0.05448],
        [0.049707, 0.017642, 0.023153],
    ],
    cov_gamma: 1.15,
    weight_px: -0.18,
    luma_ceil: 0.6,
};

/// OLED (dark).
pub const OLED: ThemeUniforms = ThemeUniforms {
    paper: [0.0, 0.0, 0.0],
    ink: [0.462077, 0.434154, 0.381326],
    ink2: [0.212231, 0.194618, 0.168269],
    accent: [0.208637, 0.304987, 0.450786],
    highlights: [
        [0.027321, 0.023153, 0.006049],
        [0.009134, 0.022174, 0.011612],
        [0.008023, 0.015996, 0.028426],
        [0.028426, 0.009721, 0.012983],
    ],
    cov_gamma: 1.2,
    weight_px: -0.22,
    luma_ceil: 0.44,
};
