/**
 * Builds the reader demo (Session C): a self-contained page that opens a real
 * Atelier-sealed Folio chunk and renders it with the production reader stack.
 *
 *   pnpm --filter @sanad/reader-demo build
 *   dist/reader-demo.html             page content (the published artifact)
 *   dist/reader-demo.standalone.html  the same, as a complete document
 *
 * Inputs come from `fixtures/folio/` (regenerated by
 * `cargo run -p sanad-atelier --example seal_reader_fixture`): the sealed
 * chunk, its dev chunk key, the atlas page (PNG) and the glyph table. The
 * compositor is the committed wasm build. The page ships no text (P1).
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { THEMES, type CssVar, type ThemeId } from "@sanad/tokens/ts";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../..");
const dist = join(here, "dist");
const folio = join(repo, "fixtures/folio");
const wasm = join(repo, "packages/lumen-wasm/pkg/sanad_compositor_bg.wasm");

if (!existsSync(join(folio, "canary-chunk0-v0.folio")) || !existsSync(join(folio, "canary-atlas0.png"))) {
  execFileSync("cargo", ["run", "-q", "-p", "sanad-atelier", "--example", "seal_reader_fixture"], {
    cwd: repo,
    stdio: ["ignore", "inherit", "inherit"],
  });
}

const meta = JSON.parse(readFileSync(join(folio, "canary-chunk0-v0.expected.json"), "utf8")) as {
  editionId: string;
  chunkKeyHex: string;
};
const glyphs = JSON.parse(readFileSync(join(folio, "canary-glyphs.json"), "utf8")) as {
  pxRange: number;
  width: number;
  height: number;
};

const data = {
  editionId: meta.editionId,
  chunkKeyHex: meta.chunkKeyHex,
  chunk: readFileSync(join(folio, "canary-chunk0-v0.folio")).toString("base64"),
  wasm: readFileSync(wasm).toString("base64"),
  atlas: {
    png: `data:image/png;base64,${readFileSync(join(folio, "canary-atlas0.png")).toString("base64")}`,
    width: glyphs.width,
    height: glyphs.height,
    pxRange: glyphs.pxRange,
  },
  glyphs: JSON.parse(readFileSync(join(folio, "canary-glyphs.json"), "utf8")),
};

const vars = (theme: ThemeId): string =>
  Object.entries(THEMES[theme].css)
    .map(([k, v]) => `${k}: ${v};`)
    .join(" ");

const THEME_BUTTONS = (Object.keys(THEMES) as ThemeId[])
  .map((id) => {
    const css = THEMES[id].css;
    const swatch = (v: CssVar): string => css[v];
    return `<button type="button" role="radio" data-theme-id="${id}" aria-checked="false" class="theme">
      <span class="theme-swatch" style="background:${swatch("--paper")};color:${swatch("--ink")};border-color:${swatch("--hairline")}">Aa</span>
      <span>${id[0]!.toUpperCase()}${id.slice(1)}</span>
    </button>`;
  })
  .join("");

function page(body: { data: string; script: string }): string {
  return `<title>Sanad Reader Demo</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Literata:opsz,wght@7..72,400&display=swap">
<style>
:root {
  ${vars("paper")}
  --font-ui: "Inter", "IBM Plex Sans Arabic", system-ui, sans-serif;
  --font-display: "Literata", Georgia, serif;
  color-scheme: light;
}
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { ${vars("night")} color-scheme: dark; } }
body { background: var(--paper); color: var(--ink); font: 400 15px/1.5 var(--font-ui); margin: 0; padding: 0 16px 48px; }
.intro { padding: 16px 0 4px; max-width: 70ch; }
.intro h1 { margin: 0; font: 600 1.3rem/1.2 var(--font-display); }
.intro p { margin: 6px 0 0; color: var(--ink-2); font-size: 0.85rem; }
.bar { position: sticky; top: 0; z-index: 2; padding: 10px 0; background: var(--paper); border-bottom: 1px solid var(--hairline); display: flex; flex-wrap: wrap; gap: 8px; }
.theme { display: inline-flex; align-items: center; gap: 8px; min-height: 40px; padding: 4px 12px 4px 4px; border: 1px solid var(--hairline); border-radius: 22px; background: var(--surface-1); color: var(--ink); font: 500 0.85rem var(--font-ui); cursor: pointer; }
.theme[aria-checked="true"] { border-color: var(--accent); box-shadow: inset 0 0 0 1px var(--accent); }
.theme-swatch { display: grid; place-items: center; width: 30px; height: 30px; border-radius: 50%; border: 1px solid; font: 600 0.8rem var(--font-display); }
.layout { display: grid; gap: 20px; margin-top: 16px; grid-template-columns: minmax(0, 1fr) minmax(220px, 300px); align-items: start; }
@media (max-width: 760px) { .layout { grid-template-columns: 1fr; } }
.stage { min-width: 0; }
#page { display: block; width: 100%; max-width: 640px; border: 1px solid var(--hairline); border-radius: 8px; background: var(--paper); }
.panel { display: grid; gap: 18px; }
.panel h2 { margin: 0 0 8px; font: 600 0.95rem var(--font-display); }
.control { display: grid; grid-template-columns: 5rem 1fr 3rem; gap: 10px; align-items: center; min-height: 40px; }
.control output { text-align: end; color: var(--ink-2); font-variant-numeric: tabular-nums; }
input[type="range"] { width: 100%; accent-color: var(--accent); }
.meta { color: var(--ink-2); font-size: 0.78rem; overflow-wrap: anywhere; font-variant-numeric: tabular-nums; }
.note { color: var(--ink-2); font-size: 0.78rem; border-inline-start: 2px solid var(--accent); padding-inline-start: 10px; }
#status { padding: 12px; border-radius: 8px; background: var(--surface-2); }
</style>
<header class="intro">
  <h1>Sanad Reader Demo</h1>
  <p>This page opens a real Folio chunk sealed by Atelier — AES-256-GCM decrypt, zstd inflate, FlatBuffer parse — lays it out with the Compositor (WebAssembly) and renders it with Lumen (WebGL2). Only a sealed chunk, an atlas and the lease key are shipped; never text.</p>
</header>
<div class="bar" role="radiogroup" aria-label="Reading theme">${THEME_BUTTONS}</div>
<main class="layout">
  <section class="stage">
    <p id="status" hidden></p>
    <canvas id="page" width="640" height="900" aria-label="A book page rendered from a sealed Folio chunk"></canvas>
  </section>
  <aside class="panel">
    <section>
      <h2>Reading</h2>
      <div class="control"><label for="size">Text size</label><input id="size" type="range" min="70" max="200" value="100"><output id="size-value">20px</output></div>
      <div class="control"><label for="warmth">Warmth</label><input id="warmth" type="range" min="0" max="100" value="0"><output id="warmth-value">0</output></div>
      <div class="control"><label for="dim">Extra dim</label><input id="dim" type="range" min="0" max="60" value="0"><output id="dim-value">0%</output></div>
    </section>
    <section>
      <h2>Pipeline</h2>
      <p class="meta" id="decoded">decoding…</p>
      <p class="meta" id="device"></p>
      <p class="note">The chunk key is the canary edition's published dev key. A real session receives a per-lease, non-extractable key over an ECDH-wrapped lease.</p>
    </section>
  </aside>
</main>
<script type="application/json" id="reader-data">${body.data}</script>
<script type="module">${body.script}</script>`;
}

const bundle = await build({
  entryPoints: [join(here, "src/app.ts")],
  bundle: true,
  write: false,
  format: "esm",
  target: "es2022",
  minify: true,
  legalComments: "none",
});
const script = (bundle.outputFiles[0]?.text ?? "").replace(/<\/script/giu, "<\\/script");
const json = JSON.stringify(data).replace(/<\//gu, "<\\/");

const body = page({ data: json, script });
mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, "reader-demo.html"), body);
writeFileSync(
  join(dist, "reader-demo.standalone.html"),
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">${body.slice(0, body.indexOf("<header"))}</head><body>${body.slice(body.indexOf("<header"))}</body></html>`,
);
const size = (Buffer.byteLength(body) / 1024 / 1024).toFixed(2);
console.log(`reader-demo: ${size} MiB → ${join(dist, "reader-demo.html")}`);
