// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod sanad {

#[allow(unused_imports, dead_code)]
pub mod folio {

#[allow(unused_imports, dead_code)]
pub mod v_1 {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_BLOCK_KIND: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_BLOCK_KIND: u8 = 7;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_BLOCK_KIND: [BlockKind; 8] = [
  BlockKind::Paragraph,
  BlockKind::Heading,
  BlockKind::Quote,
  BlockKind::ListItem,
  BlockKind::Figure,
  BlockKind::Table,
  BlockKind::Rule,
  BlockKind::Break,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct BlockKind(pub u8);
#[allow(non_upper_case_globals)]
impl BlockKind {
  pub const Paragraph: Self = Self(0);
  pub const Heading: Self = Self(1);
  pub const Quote: Self = Self(2);
  pub const ListItem: Self = Self(3);
  pub const Figure: Self = Self(4);
  pub const Table: Self = Self(5);
  pub const Rule: Self = Self(6);
  pub const Break: Self = Self(7);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 7;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Paragraph,
    Self::Heading,
    Self::Quote,
    Self::ListItem,
    Self::Figure,
    Self::Table,
    Self::Rule,
    Self::Break,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Paragraph => Some("Paragraph"),
      Self::Heading => Some("Heading"),
      Self::Quote => Some("Quote"),
      Self::ListItem => Some("ListItem"),
      Self::Figure => Some("Figure"),
      Self::Table => Some("Table"),
      Self::Rule => Some("Rule"),
      Self::Break => Some("Break"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for BlockKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for BlockKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for BlockKind {
    type Output = BlockKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for BlockKind {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for BlockKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for BlockKind {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DIRECTION: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DIRECTION: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DIRECTION: [Direction; 2] = [
  Direction::Ltr,
  Direction::Rtl,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Direction(pub u8);
#[allow(non_upper_case_globals)]
impl Direction {
  pub const Ltr: Self = Self(0);
  pub const Rtl: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Ltr,
    Self::Rtl,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Ltr => Some("Ltr"),
      Self::Rtl => Some("Rtl"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Direction {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Direction {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Direction {
    type Output = Direction;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Direction {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Direction {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Direction {}
#[allow(non_upper_case_globals)]
mod bitflags_glyph_flags {
  ::flatbuffers::bitflags::bitflags! {
    /// Per-glyph flags. Values are bit positions (bit_flags).
    #[derive(Default, Debug, Clone, Copy, PartialEq)]
    pub struct GlyphFlags: u8 {
      /// First glyph of a grapheme cluster. Anchors count clusters.
      const ClusterStart = 1;
      /// A line may break after this glyph.
      const BreakOk = 2;
      /// Inter-word glue: may stretch or shrink when justifying.
      const Glue = 4;
      /// Discretionary hyphenation point after this glyph.
      const HyphenPoint = 8;
      /// Kashida (tatweel) elongation allowed after this glyph (Arabic).
      const KashidaOk = 16;
      /// First glyph of a word (selection snapping, search highlight geometry).
      const WordStart = 32;
      /// First glyph of a sentence (sentence selection, read-aloud sync).
      const SentenceStart = 64;
      /// Never stretch around this glyph (e.g. inside numbers, URLs).
      const NoJustify = 128;
    }
  }
}
pub use self::bitflags_glyph_flags::GlyphFlags;

impl<'a> ::flatbuffers::Follow<'a> for GlyphFlags {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self::from_bits_retain(b)
  }
}

impl ::flatbuffers::Push for GlyphFlags {
    type Output = GlyphFlags;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.bits()) };
    }
}

impl ::flatbuffers::EndianScalar for GlyphFlags {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.bits().to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self::from_bits_retain(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for GlyphFlags {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for GlyphFlags {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_BODY: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_BODY: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_BODY: [Body; 3] = [
  Body::NONE,
  Body::FlowChunk,
  Body::PageChunk,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Body(pub u8);
#[allow(non_upper_case_globals)]
impl Body {
  pub const NONE: Self = Self(0);
  pub const FlowChunk: Self = Self(1);
  pub const PageChunk: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::FlowChunk,
    Self::PageChunk,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::FlowChunk => Some("FlowChunk"),
      Self::PageChunk => Some("PageChunk"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Body {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Body {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Body {
    type Output = Body;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Body {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Body {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Body {}
pub struct BodyUnionTableOffset {}

/// Mark/kerning displacement, font units.
// struct GlyphOffset, aligned to 2
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct GlyphOffset(pub [u8; 4]);
impl Default for GlyphOffset { 
  fn default() -> Self { 
    Self([0; 4])
  }
}
impl ::core::fmt::Debug for GlyphOffset {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("GlyphOffset")
      .field("x", &self.x())
      .field("y", &self.y())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for GlyphOffset {}
impl<'a> ::flatbuffers::Follow<'a> for GlyphOffset {
  type Inner = &'a GlyphOffset;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a GlyphOffset>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a GlyphOffset {
  type Inner = &'a GlyphOffset;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<GlyphOffset>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for GlyphOffset {
    type Output = GlyphOffset;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const GlyphOffset as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(2)
    }
}

impl<'a> ::flatbuffers::Verifiable for GlyphOffset {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> GlyphOffset {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: i16,
    y: i16,
  ) -> Self {
    let mut s = Self([0; 4]);
    s.set_x(x);
    s.set_y(y);
    s
  }

  pub fn x(&self) -> i16 {
    let mut mem = ::core::mem::MaybeUninit::<<i16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: i16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<i16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> i16 {
    let mut mem = ::core::mem::MaybeUninit::<<i16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<i16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: i16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        ::core::mem::size_of::<<i16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct Rect, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Rect(pub [u8; 16]);
impl Default for Rect { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl ::core::fmt::Debug for Rect {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Rect")
      .field("x", &self.x())
      .field("y", &self.y())
      .field("w", &self.w())
      .field("h", &self.h())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Rect {}
impl<'a> ::flatbuffers::Follow<'a> for Rect {
  type Inner = &'a Rect;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Rect>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Rect {
  type Inner = &'a Rect;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Rect>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Rect {
    type Output = Rect;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Rect as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for Rect {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Rect {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    x: f32,
    y: f32,
    w: f32,
    h: f32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_x(x);
    s.set_y(y);
    s.set_w(w);
    s.set_h(h);
    s
  }

  pub fn x(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn w(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_w(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn h(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_h(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[12..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

/// One positioned glyph on a fixed-layout page (PDF origin), 16 bytes.
// struct GlyphInstance, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct GlyphInstance(pub [u8; 16]);
impl Default for GlyphInstance { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl ::core::fmt::Debug for GlyphInstance {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("GlyphInstance")
      .field("gid", &self.gid())
      .field("font", &self.font())
      .field("color", &self.color())
      .field("x", &self.x())
      .field("y", &self.y())
      .field("size", &self.size())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for GlyphInstance {}
impl<'a> ::flatbuffers::Follow<'a> for GlyphInstance {
  type Inner = &'a GlyphInstance;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a GlyphInstance>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a GlyphInstance {
  type Inner = &'a GlyphInstance;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<GlyphInstance>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for GlyphInstance {
    type Output = GlyphInstance;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const GlyphInstance as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for GlyphInstance {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> GlyphInstance {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    gid: u16,
    font: u8,
    color: u8,
    x: f32,
    y: f32,
    size: f32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_gid(gid);
    s.set_font(font);
    s.set_color(color);
    s.set_x(x);
    s.set_y(y);
    s.set_size(size);
    s
  }

  /// PERMUTED glyph id.
  pub fn gid(&self) -> u16 {
    let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_gid(&mut self, x: u16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  /// Index into the manifest's font table.
  pub fn font(&self) -> u8 {
    let mut mem = ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_font(&mut self, x: u8) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  /// Ink role: 0 = ink, 1 = ink2, 2 = accent, 3+ = manifest color table.
  pub fn color(&self) -> u8 {
    let mut mem = ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[3..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_color(&mut self, x: u8) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[3..].as_mut_ptr(),
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  /// Baseline origin, points.
  pub fn x(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  /// Font size, points.
  pub fn size(&self) -> f32 {
    let mut mem = ::core::mem::MaybeUninit::<<f32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_size(&mut self, x: f32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[12..].as_mut_ptr(),
        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

/// Art-layer tile in the image pyramid (text removed at ingest).
// struct TileRef, aligned to 2
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct TileRef(pub [u8; 6]);
impl Default for TileRef { 
  fn default() -> Self { 
    Self([0; 6])
  }
}
impl ::core::fmt::Debug for TileRef {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("TileRef")
      .field("level", &self.level())
      .field("x", &self.x())
      .field("y", &self.y())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for TileRef {}
impl<'a> ::flatbuffers::Follow<'a> for TileRef {
  type Inner = &'a TileRef;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a TileRef>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a TileRef {
  type Inner = &'a TileRef;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<TileRef>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for TileRef {
    type Output = TileRef;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const TileRef as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(2)
    }
}

impl<'a> ::flatbuffers::Verifiable for TileRef {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> TileRef {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    level: u8,
    x: u16,
    y: u16,
  ) -> Self {
    let mut s = Self([0; 6]);
    s.set_level(level);
    s.set_x(x);
    s.set_y(y);
    s
  }

  pub fn level(&self) -> u8 {
    let mut mem = ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_level(&mut self, x: u8) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn x(&self) -> u16 {
    let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_x(&mut self, x: u16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn y(&self) -> u16 {
    let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_y(&mut self, x: u16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct ImagePlacement, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ImagePlacement(pub [u8; 20]);
impl Default for ImagePlacement { 
  fn default() -> Self { 
    Self([0; 20])
  }
}
impl ::core::fmt::Debug for ImagePlacement {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("ImagePlacement")
      .field("image", &self.image())
      .field("rect", &self.rect())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ImagePlacement {}
impl<'a> ::flatbuffers::Follow<'a> for ImagePlacement {
  type Inner = &'a ImagePlacement;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a ImagePlacement>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a ImagePlacement {
  type Inner = &'a ImagePlacement;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<ImagePlacement>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for ImagePlacement {
    type Output = ImagePlacement;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const ImagePlacement as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for ImagePlacement {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> ImagePlacement {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    image: u16,
    rect: &Rect,
  ) -> Self {
    let mut s = Self([0; 20]);
    s.set_image(image);
    s.set_rect(rect);
    s
  }

  pub fn image(&self) -> u16 {
    let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_image(&mut self, x: u16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn rect(&self) -> &Rect {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid struct in this slot
    unsafe { &*(self.0[4..].as_ptr() as *const Rect) }
  }

  #[allow(clippy::identity_op)]
  pub fn set_rect(&mut self, x: &Rect) {
    self.0[4..4 + 16].copy_from_slice(&x.0)
  }

}

/// Column/paragraph/panel rectangle in reading order: double-tap smart zoom,
/// guided view, selection geometry.
// struct BlockRect, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct BlockRect(pub [u8; 20]);
impl Default for BlockRect { 
  fn default() -> Self { 
    Self([0; 20])
  }
}
impl ::core::fmt::Debug for BlockRect {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("BlockRect")
      .field("rect", &self.rect())
      .field("order", &self.order())
      .field("kind", &self.kind())
      .field("dir", &self.dir())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for BlockRect {}
impl<'a> ::flatbuffers::Follow<'a> for BlockRect {
  type Inner = &'a BlockRect;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a BlockRect>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a BlockRect {
  type Inner = &'a BlockRect;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<BlockRect>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for BlockRect {
    type Output = BlockRect;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const BlockRect as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for BlockRect {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> BlockRect {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    rect: &Rect,
    order: u16,
    kind: BlockKind,
    dir: Direction,
  ) -> Self {
    let mut s = Self([0; 20]);
    s.set_rect(rect);
    s.set_order(order);
    s.set_kind(kind);
    s.set_dir(dir);
    s
  }

  pub fn rect(&self) -> &Rect {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid struct in this slot
    unsafe { &*(self.0[0..].as_ptr() as *const Rect) }
  }

  #[allow(clippy::identity_op)]
  pub fn set_rect(&mut self, x: &Rect) {
    self.0[0..0 + 16].copy_from_slice(&x.0)
  }

  pub fn order(&self) -> u16 {
    let mut mem = ::core::mem::MaybeUninit::<<u16 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_order(&mut self, x: u16) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[16..].as_mut_ptr(),
        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn kind(&self) -> BlockKind {
    let mut mem = ::core::mem::MaybeUninit::<<BlockKind as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[18..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<BlockKind as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_kind(&mut self, x: BlockKind) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[18..].as_mut_ptr(),
        ::core::mem::size_of::<<BlockKind as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn dir(&self) -> Direction {
    let mut mem = ::core::mem::MaybeUninit::<<Direction as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[19..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<Direction as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_dir(&mut self, x: Direction) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[19..].as_mut_ptr(),
        ::core::mem::size_of::<<Direction as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum RunOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A shaped run: one font, one style, one bidi direction. Structure-of-arrays:
/// every non-empty vector has exactly `gids.length` elements.
/// Glyphs are in LOGICAL order (Atelier un-reverses HarfBuzz's visual-order
/// RTL output, keeping each cluster's internal glyph order). The Compositor
/// breaks lines in logical order, then applies UAX #9 rule L2 per line at
/// cluster granularity.
pub struct Run<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Run<'a> {
  type Inner = Run<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Run<'a> {
  pub const VT_FONT: ::flatbuffers::VOffsetT = 4;
  pub const VT_STYLE: ::flatbuffers::VOffsetT = 6;
  pub const VT_GIDS: ::flatbuffers::VOffsetT = 8;
  pub const VT_ADVANCES: ::flatbuffers::VOffsetT = 10;
  pub const VT_OFFSETS: ::flatbuffers::VOffsetT = 12;
  pub const VT_FLAGS: ::flatbuffers::VOffsetT = 14;
  pub const VT_BIDI_LEVELS: ::flatbuffers::VOffsetT = 16;
  pub const VT_KASHIDA_PRIORITY: ::flatbuffers::VOffsetT = 18;
  pub const VT_KASHIDA_MAX: ::flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Run { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RunArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Run<'bldr>> {
    let mut builder = RunBuilder::new(_fbb);
    if let Some(x) = args.kashida_max { builder.add_kashida_max(x); }
    if let Some(x) = args.kashida_priority { builder.add_kashida_priority(x); }
    if let Some(x) = args.bidi_levels { builder.add_bidi_levels(x); }
    if let Some(x) = args.flags { builder.add_flags(x); }
    if let Some(x) = args.offsets { builder.add_offsets(x); }
    if let Some(x) = args.advances { builder.add_advances(x); }
    if let Some(x) = args.gids { builder.add_gids(x); }
    builder.add_style(args.style);
    builder.add_font(args.font);
    builder.finish()
  }


  /// Index into the manifest's font table.
  #[inline]
  pub fn font(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Run::VT_FONT, Some(0)).unwrap()}
  }
  /// Index into the manifest's style table (size, weight, color role, decoration).
  #[inline]
  pub fn style(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Run::VT_STYLE, Some(0)).unwrap()}
  }
  /// PERMUTED glyph ids: π_edition(font_gid). Never Unicode code points.
  #[inline]
  pub fn gids(&self) -> ::flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u16>>>(Run::VT_GIDS, None).unwrap()}
  }
  /// Horizontal advances, font units. Variant B chunks carry micro-perturbations.
  #[inline]
  pub fn advances(&self) -> ::flatbuffers::Vector<'a, i16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i16>>>(Run::VT_ADVANCES, None).unwrap()}
  }
  /// Optional per-glyph displacement; empty means all zero.
  #[inline]
  pub fn offsets(&self) -> Option<::flatbuffers::Vector<'a, GlyphOffset>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, GlyphOffset>>>(Run::VT_OFFSETS, None)}
  }
  /// GlyphFlags bitfield per glyph.
  #[inline]
  pub fn flags(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Run::VT_FLAGS, None).unwrap()}
  }
  /// UAX #9 resolved embedding level per glyph (rules up to L1 applied server-side).
  #[inline]
  pub fn bidi_levels(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Run::VT_BIDI_LEVELS, None).unwrap()}
  }
  /// Kashida priority per glyph (0 = none, 1 = highest … 7 = lowest); empty if no KashidaOk.
  #[inline]
  pub fn kashida_priority(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Run::VT_KASHIDA_PRIORITY, None)}
  }
  /// Per-glyph max kashida elongation, font units; empty if no KashidaOk.
  #[inline]
  pub fn kashida_max(&self) -> Option<::flatbuffers::Vector<'a, u16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u16>>>(Run::VT_KASHIDA_MAX, None)}
  }
}

impl ::flatbuffers::Verifiable for Run<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("font", Self::VT_FONT, false)?
     .visit_field::<u16>("style", Self::VT_STYLE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u16>>>("gids", Self::VT_GIDS, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i16>>>("advances", Self::VT_ADVANCES, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, GlyphOffset>>>("offsets", Self::VT_OFFSETS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("flags", Self::VT_FLAGS, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("bidi_levels", Self::VT_BIDI_LEVELS, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("kashida_priority", Self::VT_KASHIDA_PRIORITY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u16>>>("kashida_max", Self::VT_KASHIDA_MAX, false)?
     .finish();
    Ok(())
  }
}
pub struct RunArgs<'a> {
    pub font: u8,
    pub style: u16,
    pub gids: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u16>>>,
    pub advances: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i16>>>,
    pub offsets: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, GlyphOffset>>>,
    pub flags: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub bidi_levels: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub kashida_priority: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub kashida_max: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u16>>>,
}
impl<'a> Default for RunArgs<'a> {
  #[inline]
  fn default() -> Self {
    RunArgs {
      font: 0,
      style: 0,
      gids: None, // required field
      advances: None, // required field
      offsets: None,
      flags: None, // required field
      bidi_levels: None, // required field
      kashida_priority: None,
      kashida_max: None,
    }
  }
}

pub struct RunBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RunBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_font(&mut self, font: u8) {
    self.fbb_.push_slot::<u8>(Run::VT_FONT, font, 0);
  }
  #[inline]
  pub fn add_style(&mut self, style: u16) {
    self.fbb_.push_slot::<u16>(Run::VT_STYLE, style, 0);
  }
  #[inline]
  pub fn add_gids(&mut self, gids: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_GIDS, gids);
  }
  #[inline]
  pub fn add_advances(&mut self, advances: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_ADVANCES, advances);
  }
  #[inline]
  pub fn add_offsets(&mut self, offsets: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , GlyphOffset>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_OFFSETS, offsets);
  }
  #[inline]
  pub fn add_flags(&mut self, flags: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_FLAGS, flags);
  }
  #[inline]
  pub fn add_bidi_levels(&mut self, bidi_levels: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_BIDI_LEVELS, bidi_levels);
  }
  #[inline]
  pub fn add_kashida_priority(&mut self, kashida_priority: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_KASHIDA_PRIORITY, kashida_priority);
  }
  #[inline]
  pub fn add_kashida_max(&mut self, kashida_max: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Run::VT_KASHIDA_MAX, kashida_max);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RunBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RunBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Run<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Run::VT_GIDS,"gids");
    self.fbb_.required(o, Run::VT_ADVANCES,"advances");
    self.fbb_.required(o, Run::VT_FLAGS,"flags");
    self.fbb_.required(o, Run::VT_BIDI_LEVELS,"bidi_levels");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Run<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Run");
      ds.field("font", &self.font());
      ds.field("style", &self.style());
      ds.field("gids", &self.gids());
      ds.field("advances", &self.advances());
      ds.field("offsets", &self.offsets());
      ds.field("flags", &self.flags());
      ds.field("bidi_levels", &self.bidi_levels());
      ds.field("kashida_priority", &self.kashida_priority());
      ds.field("kashida_max", &self.kashida_max());
      ds.finish()
  }
}
pub enum ImageRefOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Figure reference. `alt_ref` is an opaque id resolved by the Kernel's a11y
/// endpoint; alt text never travels inside a chunk.
pub struct ImageRef<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ImageRef<'a> {
  type Inner = ImageRef<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ImageRef<'a> {
  pub const VT_IMAGE: ::flatbuffers::VOffsetT = 4;
  pub const VT_ALT_REF: ::flatbuffers::VOffsetT = 6;
  pub const VT_CAPTION: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ImageRef { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ImageRefArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ImageRef<'bldr>> {
    let mut builder = ImageRefBuilder::new(_fbb);
    if let Some(x) = args.caption { builder.add_caption(x); }
    builder.add_alt_ref(args.alt_ref);
    builder.add_image(args.image);
    builder.finish()
  }


  #[inline]
  pub fn image(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ImageRef::VT_IMAGE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn alt_ref(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ImageRef::VT_ALT_REF, Some(0)).unwrap()}
  }
  #[inline]
  pub fn caption(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Run<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Run>>>>(ImageRef::VT_CAPTION, None)}
  }
}

impl ::flatbuffers::Verifiable for ImageRef<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("image", Self::VT_IMAGE, false)?
     .visit_field::<u32>("alt_ref", Self::VT_ALT_REF, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Run>>>>("caption", Self::VT_CAPTION, false)?
     .finish();
    Ok(())
  }
}
pub struct ImageRefArgs<'a> {
    pub image: u16,
    pub alt_ref: u32,
    pub caption: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Run<'a>>>>>,
}
impl<'a> Default for ImageRefArgs<'a> {
  #[inline]
  fn default() -> Self {
    ImageRefArgs {
      image: 0,
      alt_ref: 0,
      caption: None,
    }
  }
}

pub struct ImageRefBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ImageRefBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_image(&mut self, image: u16) {
    self.fbb_.push_slot::<u16>(ImageRef::VT_IMAGE, image, 0);
  }
  #[inline]
  pub fn add_alt_ref(&mut self, alt_ref: u32) {
    self.fbb_.push_slot::<u32>(ImageRef::VT_ALT_REF, alt_ref, 0);
  }
  #[inline]
  pub fn add_caption(&mut self, caption: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Run<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ImageRef::VT_CAPTION, caption);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ImageRefBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ImageRefBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ImageRef<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ImageRef<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ImageRef");
      ds.field("image", &self.image());
      ds.field("alt_ref", &self.alt_ref());
      ds.field("caption", &self.caption());
      ds.finish()
  }
}
pub enum BlockOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Block<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Block<'a> {
  type Inner = Block<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Block<'a> {
  pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
  pub const VT_LEVEL: ::flatbuffers::VOffsetT = 6;
  pub const VT_STYLE: ::flatbuffers::VOffsetT = 8;
  pub const VT_DIR: ::flatbuffers::VOffsetT = 10;
  pub const VT_RUNS: ::flatbuffers::VOffsetT = 12;
  pub const VT_FIGURE: ::flatbuffers::VOffsetT = 14;
  pub const VT_KEEP_WITH_NEXT: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Block { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BlockArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Block<'bldr>> {
    let mut builder = BlockBuilder::new(_fbb);
    if let Some(x) = args.figure { builder.add_figure(x); }
    if let Some(x) = args.runs { builder.add_runs(x); }
    builder.add_style(args.style);
    builder.add_keep_with_next(args.keep_with_next);
    builder.add_dir(args.dir);
    builder.add_level(args.level);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn kind(&self) -> BlockKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BlockKind>(Block::VT_KIND, Some(BlockKind::Paragraph)).unwrap()}
  }
  /// Heading level (1–6) or list depth.
  #[inline]
  pub fn level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Block::VT_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn style(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Block::VT_STYLE, Some(0)).unwrap()}
  }
  /// Paragraph base direction.
  #[inline]
  pub fn dir(&self) -> Direction {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Direction>(Block::VT_DIR, Some(Direction::Ltr)).unwrap()}
  }
  #[inline]
  pub fn runs(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Run<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Run>>>>(Block::VT_RUNS, None)}
  }
  #[inline]
  pub fn figure(&self) -> Option<ImageRef<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ImageRef>>(Block::VT_FIGURE, None)}
  }
  /// Keep this block on the same page as the next (headings, captions).
  #[inline]
  pub fn keep_with_next(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Block::VT_KEEP_WITH_NEXT, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Block<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<BlockKind>("kind", Self::VT_KIND, false)?
     .visit_field::<u8>("level", Self::VT_LEVEL, false)?
     .visit_field::<u16>("style", Self::VT_STYLE, false)?
     .visit_field::<Direction>("dir", Self::VT_DIR, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Run>>>>("runs", Self::VT_RUNS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ImageRef>>("figure", Self::VT_FIGURE, false)?
     .visit_field::<bool>("keep_with_next", Self::VT_KEEP_WITH_NEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct BlockArgs<'a> {
    pub kind: BlockKind,
    pub level: u8,
    pub style: u16,
    pub dir: Direction,
    pub runs: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Run<'a>>>>>,
    pub figure: Option<::flatbuffers::WIPOffset<ImageRef<'a>>>,
    pub keep_with_next: bool,
}
impl<'a> Default for BlockArgs<'a> {
  #[inline]
  fn default() -> Self {
    BlockArgs {
      kind: BlockKind::Paragraph,
      level: 0,
      style: 0,
      dir: Direction::Ltr,
      runs: None,
      figure: None,
      keep_with_next: false,
    }
  }
}

pub struct BlockBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BlockBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_kind(&mut self, kind: BlockKind) {
    self.fbb_.push_slot::<BlockKind>(Block::VT_KIND, kind, BlockKind::Paragraph);
  }
  #[inline]
  pub fn add_level(&mut self, level: u8) {
    self.fbb_.push_slot::<u8>(Block::VT_LEVEL, level, 0);
  }
  #[inline]
  pub fn add_style(&mut self, style: u16) {
    self.fbb_.push_slot::<u16>(Block::VT_STYLE, style, 0);
  }
  #[inline]
  pub fn add_dir(&mut self, dir: Direction) {
    self.fbb_.push_slot::<Direction>(Block::VT_DIR, dir, Direction::Ltr);
  }
  #[inline]
  pub fn add_runs(&mut self, runs: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Run<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Block::VT_RUNS, runs);
  }
  #[inline]
  pub fn add_figure(&mut self, figure: ::flatbuffers::WIPOffset<ImageRef<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ImageRef>>(Block::VT_FIGURE, figure);
  }
  #[inline]
  pub fn add_keep_with_next(&mut self, keep_with_next: bool) {
    self.fbb_.push_slot::<bool>(Block::VT_KEEP_WITH_NEXT, keep_with_next, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BlockBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BlockBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Block<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Block<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Block");
      ds.field("kind", &self.kind());
      ds.field("level", &self.level());
      ds.field("style", &self.style());
      ds.field("dir", &self.dir());
      ds.field("runs", &self.runs());
      ds.field("figure", &self.figure());
      ds.field("keep_with_next", &self.keep_with_next());
      ds.finish()
  }
}
pub enum FlowChunkOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Reflowable content: shaped, NOT line-broken (blueprint decision D1).
/// Blocks are whole paragraphs; chunk boundaries never split a paragraph.
pub struct FlowChunk<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FlowChunk<'a> {
  type Inner = FlowChunk<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FlowChunk<'a> {
  pub const VT_BLOCKS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FlowChunk { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FlowChunkArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FlowChunk<'bldr>> {
    let mut builder = FlowChunkBuilder::new(_fbb);
    if let Some(x) = args.blocks { builder.add_blocks(x); }
    builder.finish()
  }


  #[inline]
  pub fn blocks(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Block<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Block>>>>(FlowChunk::VT_BLOCKS, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for FlowChunk<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Block>>>>("blocks", Self::VT_BLOCKS, true)?
     .finish();
    Ok(())
  }
}
pub struct FlowChunkArgs<'a> {
    pub blocks: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Block<'a>>>>>,
}
impl<'a> Default for FlowChunkArgs<'a> {
  #[inline]
  fn default() -> Self {
    FlowChunkArgs {
      blocks: None, // required field
    }
  }
}

pub struct FlowChunkBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FlowChunkBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_blocks(&mut self, blocks: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Block<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FlowChunk::VT_BLOCKS, blocks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FlowChunkBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FlowChunkBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FlowChunk<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FlowChunk::VT_BLOCKS,"blocks");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FlowChunk<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FlowChunk");
      ds.field("blocks", &self.blocks());
      ds.finish()
  }
}
pub enum PageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Page<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Page<'a> {
  type Inner = Page<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Page<'a> {
  pub const VT_WIDTH: ::flatbuffers::VOffsetT = 4;
  pub const VT_HEIGHT: ::flatbuffers::VOffsetT = 6;
  pub const VT_GLYPHS: ::flatbuffers::VOffsetT = 8;
  pub const VT_ART_TILES: ::flatbuffers::VOffsetT = 10;
  pub const VT_IMAGES: ::flatbuffers::VOffsetT = 12;
  pub const VT_BLOCKS: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Page { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PageArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Page<'bldr>> {
    let mut builder = PageBuilder::new(_fbb);
    if let Some(x) = args.blocks { builder.add_blocks(x); }
    if let Some(x) = args.images { builder.add_images(x); }
    if let Some(x) = args.art_tiles { builder.add_art_tiles(x); }
    if let Some(x) = args.glyphs { builder.add_glyphs(x); }
    builder.add_height(args.height);
    builder.add_width(args.width);
    builder.finish()
  }


  #[inline]
  pub fn width(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Page::VT_WIDTH, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Page::VT_HEIGHT, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn glyphs(&self) -> Option<::flatbuffers::Vector<'a, GlyphInstance>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, GlyphInstance>>>(Page::VT_GLYPHS, None)}
  }
  #[inline]
  pub fn art_tiles(&self) -> Option<::flatbuffers::Vector<'a, TileRef>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, TileRef>>>(Page::VT_ART_TILES, None)}
  }
  #[inline]
  pub fn images(&self) -> Option<::flatbuffers::Vector<'a, ImagePlacement>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ImagePlacement>>>(Page::VT_IMAGES, None)}
  }
  #[inline]
  pub fn blocks(&self) -> Option<::flatbuffers::Vector<'a, BlockRect>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, BlockRect>>>(Page::VT_BLOCKS, None)}
  }
}

impl ::flatbuffers::Verifiable for Page<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<f32>("width", Self::VT_WIDTH, false)?
     .visit_field::<f32>("height", Self::VT_HEIGHT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, GlyphInstance>>>("glyphs", Self::VT_GLYPHS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, TileRef>>>("art_tiles", Self::VT_ART_TILES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ImagePlacement>>>("images", Self::VT_IMAGES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, BlockRect>>>("blocks", Self::VT_BLOCKS, false)?
     .finish();
    Ok(())
  }
}
pub struct PageArgs<'a> {
    pub width: f32,
    pub height: f32,
    pub glyphs: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, GlyphInstance>>>,
    pub art_tiles: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, TileRef>>>,
    pub images: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ImagePlacement>>>,
    pub blocks: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, BlockRect>>>,
}
impl<'a> Default for PageArgs<'a> {
  #[inline]
  fn default() -> Self {
    PageArgs {
      width: 0.0,
      height: 0.0,
      glyphs: None,
      art_tiles: None,
      images: None,
      blocks: None,
    }
  }
}

pub struct PageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_width(&mut self, width: f32) {
    self.fbb_.push_slot::<f32>(Page::VT_WIDTH, width, 0.0);
  }
  #[inline]
  pub fn add_height(&mut self, height: f32) {
    self.fbb_.push_slot::<f32>(Page::VT_HEIGHT, height, 0.0);
  }
  #[inline]
  pub fn add_glyphs(&mut self, glyphs: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , GlyphInstance>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Page::VT_GLYPHS, glyphs);
  }
  #[inline]
  pub fn add_art_tiles(&mut self, art_tiles: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , TileRef>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Page::VT_ART_TILES, art_tiles);
  }
  #[inline]
  pub fn add_images(&mut self, images: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ImagePlacement>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Page::VT_IMAGES, images);
  }
  #[inline]
  pub fn add_blocks(&mut self, blocks: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , BlockRect>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Page::VT_BLOCKS, blocks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Page<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Page<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Page");
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.field("glyphs", &self.glyphs());
      ds.field("art_tiles", &self.art_tiles());
      ds.field("images", &self.images());
      ds.field("blocks", &self.blocks());
      ds.finish()
  }
}
pub enum PageChunkOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PageChunk<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PageChunk<'a> {
  type Inner = PageChunk<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PageChunk<'a> {
  pub const VT_PAGES: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PageChunk { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PageChunkArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PageChunk<'bldr>> {
    let mut builder = PageChunkBuilder::new(_fbb);
    if let Some(x) = args.pages { builder.add_pages(x); }
    builder.finish()
  }


  #[inline]
  pub fn pages(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Page<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Page>>>>(PageChunk::VT_PAGES, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for PageChunk<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Page>>>>("pages", Self::VT_PAGES, true)?
     .finish();
    Ok(())
  }
}
pub struct PageChunkArgs<'a> {
    pub pages: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Page<'a>>>>>,
}
impl<'a> Default for PageChunkArgs<'a> {
  #[inline]
  fn default() -> Self {
    PageChunkArgs {
      pages: None, // required field
    }
  }
}

pub struct PageChunkBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PageChunkBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_pages(&mut self, pages: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Page<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PageChunk::VT_PAGES, pages);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PageChunkBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PageChunkBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PageChunk<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PageChunk::VT_PAGES,"pages");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PageChunk<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PageChunk");
      ds.field("pages", &self.pages());
      ds.finish()
  }
}
pub enum PayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Payload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Payload<'a> {
  type Inner = Payload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Payload<'a> {
  pub const VT_BODY_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_BODY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Payload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PayloadArgs
  ) -> ::flatbuffers::WIPOffset<Payload<'bldr>> {
    let mut builder = PayloadBuilder::new(_fbb);
    if let Some(x) = args.body { builder.add_body(x); }
    builder.add_body_type(args.body_type);
    builder.finish()
  }


  #[inline]
  pub fn body_type(&self) -> Body {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Body>(Payload::VT_BODY_TYPE, Some(Body::NONE)).unwrap()}
  }
  /// Must agree with the container header's `kind` (checked by the codec).
  #[inline]
  pub fn body(&self) -> ::flatbuffers::Table<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Payload::VT_BODY, None).unwrap()}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_flow_chunk(&self) -> Option<FlowChunk<'a>> {
    if self.body_type() == Body::FlowChunk {
      let u = self.body();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { FlowChunk::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_page_chunk(&self) -> Option<PageChunk<'a>> {
    if self.body_type() == Body::PageChunk {
      let u = self.body();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { PageChunk::init_from_table(u) })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for Payload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<Body, _>("body_type", Self::VT_BODY_TYPE, "body", Self::VT_BODY, true, |key, v, pos| {
        match key {
          Body::FlowChunk => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<FlowChunk>>("Body::FlowChunk", pos),
          Body::PageChunk => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<PageChunk>>("Body::PageChunk", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct PayloadArgs {
    pub body_type: Body,
    pub body: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for PayloadArgs {
  #[inline]
  fn default() -> Self {
    PayloadArgs {
      body_type: Body::NONE,
      body: None, // required field
    }
  }
}

pub struct PayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_body_type(&mut self, body_type: Body) {
    self.fbb_.push_slot::<Body>(Payload::VT_BODY_TYPE, body_type, Body::NONE);
  }
  #[inline]
  pub fn add_body(&mut self, body: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Payload::VT_BODY, body);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Payload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Payload::VT_BODY,"body");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Payload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Payload");
      ds.field("body_type", &self.body_type());
      match self.body_type() {
        Body::FlowChunk => {
          if let Some(x) = self.body_as_flow_chunk() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Body::PageChunk => {
          if let Some(x) = self.body_as_page_chunk() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("body", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Payload`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_payload_unchecked`.
pub fn root_as_payload(buf: &[u8]) -> Result<Payload<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Payload>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Payload` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_payload_unchecked`.
pub fn size_prefixed_root_as_payload(buf: &[u8]) -> Result<Payload<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Payload>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Payload` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_payload_unchecked`.
pub fn root_as_payload_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Payload<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Payload<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Payload` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_payload_unchecked`.
pub fn size_prefixed_root_as_payload_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Payload<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Payload<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Payload and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Payload`.
pub unsafe fn root_as_payload_unchecked(buf: &[u8]) -> Payload<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Payload>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Payload and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Payload`.
pub unsafe fn size_prefixed_root_as_payload_unchecked(buf: &[u8]) -> Payload<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Payload>(buf) }
}
pub const PAYLOAD_IDENTIFIER: &str = "FOL1";

#[inline]
pub fn payload_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PAYLOAD_IDENTIFIER, false)
}

#[inline]
pub fn payload_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PAYLOAD_IDENTIFIER, true)
}

pub const PAYLOAD_EXTENSION: &str = "folio";

#[inline]
pub fn finish_payload_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Payload<'a>>) {
  fbb.finish(root, Some(PAYLOAD_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_payload_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Payload<'a>>) {
  fbb.finish_size_prefixed(root, Some(PAYLOAD_IDENTIFIER));
}
}  // pub mod v1
}  // pub mod folio
}  // pub mod sanad

